import { render, screen } from '@testing-library/react'
import RootLayout, { metadata } from './layout'

// Mock the Next.js fonts
jest.mock('next/font/google', () => ({
  Geist: () => ({
    variable: '--font-geist-sans',
    subsets: ['latin'],
  }),
  Geist_Mono: () => ({
    variable: '--font-geist-mono',
    subsets: ['latin'],
  }),
}))

describe('RootLayout', () => {
  it('renders children correctly', () => {
    render(
      <RootLayout>
        <div data-testid="test-child">Test Child Content</div>
      </RootLayout>
    )
    
    const child = screen.getByTestId('test-child')
    expect(child).toBeInTheDocument()
    expect(child).toHaveTextContent('Test Child Content')
  })

  it('has correct metadata', () => {
    expect(metadata.title).toBe('Create Next App')
    expect(metadata.description).toBe('Generated by create next app')
  })

  it('wraps children in proper structure', () => {
    const { container } = render(
      <RootLayout>
        <main>Main Content</main>
      </RootLayout>
    )
    
    const main = container.querySelector('main')
    expect(main).toBeInTheDocument()
    expect(main).toHaveTextContent('Main Content')
  })
})
