name: Merge dependabot PRs

on:
  pull_request:

permissions: write-all

jobs:
  merge-pr:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # ratchet:actions/checkout@v5
        with:
          persist-credentials: false
      - name: Merge PR with
        run: gh pr merge ${{ github.event.pull_request.number }} --merge --admin
